"""Coverage matrix for formal agent integration."""

from __future__ import annotations

from pathlib import Path
from typing import Any

EXPECTED_BY_MODE = {
    "quick": ["model_response", "openai_tool_calls", "gateway", "stable_session_identity", "audit_log", "agent_env", "agent_instructions"],
    "standard": [
        "model_response",
        "openai_tool_calls",
        "gateway",
        "stable_session_identity",
        "audit_log",
        "agent_env",
        "agent_instructions",
        "guarded_tool_shims",
        "file_guard",
        "exec_guard",
        "package_install",
        "mcp_tool",
    ],
    "full": [
        "model_response",
        "openai_tool_calls",
        "gateway",
        "stable_session_identity",
        "audit_log",
        "agent_env",
        "agent_instructions",
        "guarded_tool_shims",
        "file_guard",
        "exec_guard",
        "studio",
        "approval_api",
        "demo_package",
        "audit_evidence_graph",
    ],
}


def build_coverage_report(config: dict[str, Any], checks: dict[str, bool] | None = None) -> dict[str, Any]:
    mode = str(config.get("mode") or "quick")
    expected = EXPECTED_BY_MODE.get(mode, EXPECTED_BY_MODE["quick"])
    checks = checks or {}
    capabilities = set(config.get("capabilities") or [])
    rows = []
    for name in expected:
        declared = name in capabilities
        verified = bool(checks.get(name, declared))
        status = "protected" if declared and verified else "partial" if declared else "missing"
        if name in {"mcp_tool", "file_guard"} and declared and not verified:
            status = "partial"
        rows.append(
            {"capability": name, "declared": declared, "verified": verified, "status": status, "evidence": _evidence(name, verified)}
        )
    missing = [row["capability"] for row in rows if row["status"] == "missing"]
    return {"mode": mode, "ok": not missing, "missing": missing, "matrix": rows}


def filesystem_checks(config: dict[str, Any]) -> dict[str, bool]:
    repo = Path(str(config["repo_root"]))
    checks = {
        "gateway": bool(config.get("gateway", {}).get("enabled")),
        "model_response": bool(config.get("gateway", {}).get("enabled")),
        "openai_tool_calls": bool(config.get("gateway", {}).get("enabled")),
        "stable_session_identity": bool(config.get("session", {}).get("run_id") and config.get("session", {}).get("conversation_id")),
        "audit_log": Path(str(config.get("audit", {}).get("path", repo / ".agentbrake" / "gateway_audit.jsonl"))).parent.exists(),
        "agent_env": (repo / ".agentbrake" / "agent.env").exists(),
        "agent_instructions": (repo / ".agentbrake" / "agent-instructions.md").exists(),
        "guarded_tool_shims": bool(config.get("shims", {}).get("enabled")) and Path(str(config.get("shims", {}).get("path", ""))).exists(),
        "file_guard": bool(config.get("shims", {}).get("enabled")),
        "exec_guard": bool(config.get("shims", {}).get("enabled")),
        "package_install": bool(config.get("shims", {}).get("enabled")),
        "mcp_tool": False,
        "studio": not config.get("studio", {}).get("enabled") or bool(config.get("studio", {}).get("port")),
        "approval_api": not config.get("approval", {}).get("enabled") or bool(config.get("approval", {}).get("store")),
        "demo_package": not config.get("demo", {}).get("enabled")
        or (
            Path(str(config.get("demo", {}).get("normal_request", ""))).exists()
            and Path(str(config.get("demo", {}).get("attack_request", ""))).exists()
        ),
        "audit_evidence_graph": Path(
            str(config.get("audit", {}).get("path", repo / ".agentbrake" / "gateway_audit.jsonl"))
        ).parent.exists(),
    }
    return checks


def _evidence(name: str, verified: bool) -> str:
    if verified:
        return {
            "model_response": "Gateway configured",
            "openai_tool_calls": "Gateway ToolMappingRegistry path configured",
            "stable_session_identity": "run_id and conversation_id configured",
            "guarded_tool_shims": "shim directory exists",
            "package_install": "package-manager shims configured",
            "audit_evidence_graph": "audit directory is available",
        }.get(name, "configured")
    return {
        "mcp_tool": "MCP proxy is not generated by connect yet",
        "file_guard": "file guard requires agent/tool integration or shims",
        "guarded_tool_shims": "shim directory missing or disabled",
    }.get(name, "not verified")
